import AppKit
import Carbon
import ApplicationServices
import UniformTypeIdentifiers

let generatedEventTag: Int64 = 0x534E4950
let ignoredApps = ["com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop", "com.apple.keychainaccess", "com.apple.Passwords"]

final class ClipboardService {
    let history: History
    let usage: UsageStore?
    var timer: Timer?
    let board: NSPasteboard
    let enabled: () -> Bool
    var changeCount: Int
    var ticks = 0
    private var activity: NSObjectProtocol?
    init(history: History, usage: UsageStore? = nil, board: NSPasteboard = .general, enabled: @escaping () -> Bool = { AppEnvironment.defaults.bool(forKey: "historyEnabled") }) {
        self.history = history; self.usage = usage; self.board = board; self.enabled = enabled; self.changeCount = board.changeCount
    }
    func start() {
        history.prune()
        let timer = Timer(timeInterval: 0.25, repeats: true) { [weak self] _ in self?.poll() }
        timer.tolerance = 0.05
        // Common modes keep polling while a menu, sheet or drag is tracking.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }
    func poll() {
        ticks += 1
        if ticks % 240 == 0 { history.prune() }
        let isEnabled = enabled()
        // App Nap can stretch a background timer to many seconds, so a second
        // copy would replace the first before it was ever seen.
        if isEnabled, activity == nil { activity = ProcessInfo.processInfo.beginActivity(options: .userInitiatedAllowingIdleSystemSleep, reason: "Recording clipboard history") }
        else if !isEnabled, let current = activity { ProcessInfo.processInfo.endActivity(current); activity = nil }
        guard board.changeCount != changeCount else { return }
        changeCount = board.changeCount
        guard isEnabled else { return }
        let types = board.types ?? []
        let ignored = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
        guard !types.contains(where: { ignored.contains($0.rawValue) }) else { return }
        let app = NSWorkspace.shared.frontmostApplication
        guard !ignoredApps.contains(app?.bundleIdentifier ?? "") else { return }
        let source = app?.localizedName ?? "Clipboard"
        let text = Self.text(on: board)
        if Self.prefersImage(types, hasText: text != nil), let image = NSImage(pasteboard: board) {
            history.recordImage(image, source: source)
        } else if let text, let result = history.record(text, source: source), result.recopied {
            usage?.record(UsageStore.key(clip: result.id))
        }
    }
    /// Office, iWork and many editors add a picture of copied text as a fallback.
    /// Writers list their preferred representation first, so an image only wins
    /// when it comes before any text, or when there is no text at all.
    static func prefersImage(_ types: [NSPasteboard.PasteboardType], hasText: Bool) -> Bool {
        guard let image = types.firstIndex(where: { $0 == .png || $0 == .tiff }) else { return false }
        guard hasText else { return true }
        let text = types.firstIndex { UTType($0.rawValue)?.conforms(to: .text) == true } ?? types.endIndex
        return image < text
    }
    /// Plain text, or the text of rich-text-only copies. HTML is skipped: importing it loads WebKit on the main thread.
    static func text(on board: NSPasteboard) -> String? {
        func meaningful(_ text: String?) -> String? { text?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false ? text : nil }
        if let plain = meaningful(board.string(forType: .string)) { return plain }
        for (type, format) in [(NSPasteboard.PasteboardType.rtf, NSAttributedString.DocumentType.rtf), (.rtfd, .rtfd)] {
            if let data = board.data(forType: type), let text = meaningful(try? NSAttributedString(data: data, options: [.documentType: format], documentAttributes: nil).string) { return text }
        }
        return nil
    }
}

func postKey(_ code: CGKeyCode, flags: CGEventFlags = [], proxy: CGEventTapProxy? = nil) {
    for isDown in [true, false] {
        let event = CGEvent(keyboardEventSource: nil, virtualKey: code, keyDown: isDown)
        event?.flags = flags
        event?.setIntegerValueField(.eventSourceUserData, value: generatedEventTag)
        if let proxy { event?.tapPostEvent(proxy) } else { event?.post(tap: .cghidEventTap) }
    }
}

/// Command–V for the frontmost app. The source briefly suppresses local key
/// events so physical keys can't interleave with the synthetic shortcut, and
/// the left-Command device bit (0x8) satisfies apps that check which key is held.
func postPaste() {
    let source = CGEventSource(stateID: .combinedSessionState)
    source?.setLocalEventsFilterDuringSuppressionState([.permitLocalMouseEvents, .permitSystemDefinedEvents], state: .eventSuppressionStateSuppressionInterval)
    for isDown in [true, false] {
        let event = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: isDown)
        event?.flags = [.maskCommand, CGEventFlags(rawValue: 0x8)]
        event?.setIntegerValueField(.eventSourceUserData, value: generatedEventTag)
        event?.post(tap: .cgSessionEventTap)
    }
}

/// A click on a result hides the launcher immediately. If that click was the
/// first half of a double-click, the second half would land in the destination
/// and select a word for the paste to replace. Swallow it for one interval.
final class FollowUpClickGuard {
    private var tap: CFMachPort?
    private var source: CFRunLoopSource?
    private var deadline = Date.distantPast
    private var swallowingUp = false
    func arm(for interval: TimeInterval = NSEvent.doubleClickInterval) {
        deadline = Date().addingTimeInterval(interval)
        DispatchQueue.main.asyncAfter(deadline: .now() + interval + 0.05) { [weak self] in self?.disarmIfExpired() }
        guard tap == nil, AXIsProcessTrusted() else { return }
        let mask = (1 << CGEventType.leftMouseDown.rawValue) | (1 << CGEventType.leftMouseUp.rawValue)
        tap = CGEvent.tapCreate(tap: .cgSessionEventTap, place: .headInsertEventTap, options: .defaultTap, eventsOfInterest: CGEventMask(mask), callback: { _, type, event, context in
            guard let context else { return Unmanaged.passUnretained(event) }
            return Unmanaged<FollowUpClickGuard>.fromOpaque(context).takeUnretainedValue().filter(type, event)
        }, userInfo: Unmanaged.passUnretained(self).toOpaque())
        guard let tap else { return }
        source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0)
        CFRunLoopAddSource(CFRunLoopGetMain(), source, .commonModes)
        CGEvent.tapEnable(tap: tap, enable: true)
    }
    private func filter(_ type: CGEventType, _ event: CGEvent) -> Unmanaged<CGEvent>? {
        if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
            if let tap { CGEvent.tapEnable(tap: tap, enable: true) }
            return Unmanaged.passUnretained(event)
        }
        if type == .leftMouseUp && swallowingUp { swallowingUp = false; return nil }
        guard type == .leftMouseDown, Date() < deadline, event.getIntegerValueField(.mouseEventClickState) >= 2 else { return Unmanaged.passUnretained(event) }
        swallowingUp = true
        return nil
    }
    private func disarmIfExpired() {
        guard Date() >= deadline, !swallowingUp else {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) { [weak self] in self?.disarmIfExpired() }
            return
        }
        if let tap { CFMachPortInvalidate(tap) }
        if let source { CFRunLoopRemoveSource(CFRunLoopGetMain(), source, .commonModes) }
        tap = nil; source = nil
    }
}

final class ExpansionService: ObservableObject {
    let store: Store
    @Published var status = "Off"
    @Published private(set) var accessibilityTrusted = AXIsProcessTrusted()
    var tap: CFMachPort?
    var source: CFRunLoopSource?
    var timer: Timer?
    var matcher = ExpansionMatcher()
    var lastPID: pid_t = 0
    var lastTime = Date.distantPast
    init(store: Store) { self.store = store }
    func start() { timer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { [weak self] _ in self?.update() }; update() }
    func update() {
        let trusted = AXIsProcessTrusted()
        if trusted != accessibilityTrusted { accessibilityTrusted = trusted }
        guard AppEnvironment.defaults.bool(forKey: "expansionEnabled") else { stop(); status = "Off"; return }
        guard trusted else { stop(); status = "Needs Accessibility access"; return }
        guard tap == nil else { status = "Ready — type a snippet’s ;keyword"; return }
        let mask = (1 << CGEventType.keyDown.rawValue) | (1 << CGEventType.leftMouseDown.rawValue) | (1 << CGEventType.rightMouseDown.rawValue)
        tap = CGEvent.tapCreate(tap: .cgSessionEventTap, place: .headInsertEventTap, options: .defaultTap, eventsOfInterest: CGEventMask(mask), callback: { proxy, type, event, context in
            guard let context else { return Unmanaged.passUnretained(event) }
            return Unmanaged<ExpansionService>.fromOpaque(context).takeUnretainedValue().receive(proxy, type, event)
        }, userInfo: Unmanaged.passUnretained(self).toOpaque())
        guard let tap else { status = "Couldn’t start. Check Accessibility access, then reopen Snippet."; return }
        source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0)
        CFRunLoopAddSource(CFRunLoopGetMain(), source, .commonModes)
        CGEvent.tapEnable(tap: tap, enable: true)
        status = "Ready — type a snippet’s ;keyword"
    }
    func stop() {
        if let tap { CFMachPortInvalidate(tap) }
        if let source { CFRunLoopRemoveSource(CFRunLoopGetMain(), source, .commonModes) }
        tap = nil; source = nil; matcher.reset()
    }
    func receive(_ proxy: CGEventTapProxy, _ type: CGEventType, _ event: CGEvent) -> Unmanaged<CGEvent>? {
        if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
            matcher.reset(); if let tap { CGEvent.tapEnable(tap: tap, enable: true) }
            return Unmanaged.passUnretained(event)
        }
        if event.getIntegerValueField(.eventSourceUserData) == generatedEventTag { return Unmanaged.passUnretained(event) }
        guard type == .keyDown, !IsSecureEventInputEnabled(), AppEnvironment.defaults.bool(forKey: "expansionEnabled") else { matcher.reset(); return Unmanaged.passUnretained(event) }
        let front = NSWorkspace.shared.frontmostApplication
        guard let pid = front?.processIdentifier, pid != ProcessInfo.processInfo.processIdentifier, !ignoredApps.contains(front?.bundleIdentifier ?? "") else { matcher.reset(); return Unmanaged.passUnretained(event) }
        if pid != lastPID || Date().timeIntervalSince(lastTime) > 3 { matcher.reset() }
        lastPID = pid; lastTime = Date()
        let code = event.getIntegerValueField(.keyboardEventKeycode)
        guard !event.flags.contains(.maskCommand), !event.flags.contains(.maskControl), !event.flags.contains(.maskAlternate), ![51, 53, 123, 124, 125, 126, 36, 48, 117].contains(code) else { matcher.reset(); return Unmanaged.passUnretained(event) }
        var length = 0
        var chars = [UniChar](repeating: 0, count: 8)
        event.keyboardGetUnicodeString(maxStringLength: 8, actualStringLength: &length, unicodeString: &chars)
        let text = String(utf16CodeUnits: chars, count: length)
        guard let item = matcher.feed(text, snippets: store.items), item.text.utf16.count <= 2000, let keyword = item.keyword else { return Unmanaged.passUnretained(event) }
        guard SnippetTemplate.fields(item.text).isEmpty else { return Unmanaged.passUnretained(event) }
        let expanded = SnippetTemplate.expand(item.text, clipboard: NSPasteboard.general.string(forType: .string) ?? "")
        guard expanded.text.utf16.count <= 2000 else { return Unmanaged.passUnretained(event) }
        // The final keyword character is suppressed; delete only characters already delivered.
        for _ in 0..<(keyword.count - 1) { postKey(CGKeyCode(kVK_Delete), proxy: proxy) }
        // Unicode events avoid changing the clipboard during expansion.
        var chunks: [[UniChar]] = []
        var current: [UniChar] = []
        for scalar in expanded.text.unicodeScalars {
            let units = Array(String(scalar).utf16)
            if current.count + units.count > 20 { chunks.append(current); current = [] }
            current.append(contentsOf: units)
        }
        if !current.isEmpty { chunks.append(current) }
        for chunk in chunks {
            let output = CGEvent(keyboardEventSource: nil, virtualKey: 0, keyDown: true)
            output?.flags = []
            output?.setIntegerValueField(.eventSourceUserData, value: generatedEventTag)
            chunk.withUnsafeBufferPointer { output?.keyboardSetUnicodeString(stringLength: chunk.count, unicodeString: $0.baseAddress) }
            output?.tapPostEvent(proxy)
            let up = CGEvent(keyboardEventSource: nil, virtualKey: 0, keyDown: false)
            up?.flags = []; up?.setIntegerValueField(.eventSourceUserData, value: generatedEventTag); up?.tapPostEvent(proxy)
        }
        for _ in 0..<min(expanded.cursorMoves, 2000) { postKey(CGKeyCode(kVK_LeftArrow), proxy: proxy) }
        return nil
    }
}
