import AppKit
import Carbon
import ApplicationServices

let generatedEventTag: Int64 = 0x534E4950
let ignoredApps = ["com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop", "com.apple.keychainaccess", "com.apple.Passwords"]

final class ClipboardService {
    let history: History
    var timer: Timer?
    let board: NSPasteboard
    let enabled: () -> Bool
    var changeCount: Int
    var ticks = 0
    init(history: History, board: NSPasteboard = .general, enabled: @escaping () -> Bool = { UserDefaults.standard.bool(forKey: "historyEnabled") }) {
        self.history = history; self.board = board; self.enabled = enabled; self.changeCount = board.changeCount
    }
    func start() {
        history.prune()
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in self?.poll() }
    }
    func poll() {
        ticks += 1
        if ticks % 150 == 0 { history.prune() }
        guard board.changeCount != changeCount else { return }
        changeCount = board.changeCount
        guard enabled() else { return }
        let ignored = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
        guard !(board.types ?? []).contains(where: { ignored.contains($0.rawValue) }) else { return }
        let app = NSWorkspace.shared.frontmostApplication
        guard !ignoredApps.contains(app?.bundleIdentifier ?? ""), let text = board.string(forType: .string) else { return }
        history.record(text, source: app?.localizedName ?? "Clipboard")
    }
}

func postKey(_ code: CGKeyCode, flags: CGEventFlags = [], proxy: CGEventTapProxy? = nil) {
    for isDown in [true, false] {
        let event = CGEvent(keyboardEventSource: nil, virtualKey: code, keyDown: isDown)
        event?.flags = flags
        event?.setIntegerValueField(.eventSourceUserData, value: generatedEventTag)
        if let proxy { event?.tapPostEvent(proxy) } else { event?.post(tap: .cghidEventTap) }
    }
}

final class ExpansionService: ObservableObject {
    let store: Store
    @Published var status = "Off"
    var tap: CFMachPort?
    var source: CFRunLoopSource?
    var timer: Timer?
    var matcher = ExpansionMatcher()
    var lastPID: pid_t = 0
    var lastTime = Date.distantPast
    init(store: Store) { self.store = store }
    func start() { timer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { [weak self] _ in self?.update() }; update() }
    func update() {
        guard UserDefaults.standard.bool(forKey: "expansionEnabled") else { stop(); status = "Off"; return }
        guard AXIsProcessTrusted() else { stop(); status = "Needs Accessibility access"; return }
        guard tap == nil else { status = "Ready — type a snippet’s ;keyword"; return }
        let mask = (1 << CGEventType.keyDown.rawValue) | (1 << CGEventType.leftMouseDown.rawValue) | (1 << CGEventType.rightMouseDown.rawValue)
        tap = CGEvent.tapCreate(tap: .cgSessionEventTap, place: .headInsertEventTap, options: .defaultTap, eventsOfInterest: CGEventMask(mask), callback: { proxy, type, event, context in
            guard let context else { return Unmanaged.passUnretained(event) }
            return Unmanaged<ExpansionService>.fromOpaque(context).takeUnretainedValue().receive(proxy, type, event)
        }, userInfo: Unmanaged.passUnretained(self).toOpaque())
        guard let tap else { status = "Couldn’t start. Check Accessibility access, then reopen Snippet."; return }
        source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0)
        CFRunLoopAddSource(CFRunLoopGetMain(), source, .commonModes)
        CGEvent.tapEnable(tap: tap, enable: true)
        status = "Ready — type a snippet’s ;keyword"
    }
    func stop() {
        if let tap { CFMachPortInvalidate(tap) }
        if let source { CFRunLoopRemoveSource(CFRunLoopGetMain(), source, .commonModes) }
        tap = nil; source = nil; matcher.reset()
    }
    func receive(_ proxy: CGEventTapProxy, _ type: CGEventType, _ event: CGEvent) -> Unmanaged<CGEvent>? {
        if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
            matcher.reset(); if let tap { CGEvent.tapEnable(tap: tap, enable: true) }
            return Unmanaged.passUnretained(event)
        }
        if event.getIntegerValueField(.eventSourceUserData) == generatedEventTag { return Unmanaged.passUnretained(event) }
        guard type == .keyDown, !IsSecureEventInputEnabled(), UserDefaults.standard.bool(forKey: "expansionEnabled") else { matcher.reset(); return Unmanaged.passUnretained(event) }
        let front = NSWorkspace.shared.frontmostApplication
        guard let pid = front?.processIdentifier, pid != ProcessInfo.processInfo.processIdentifier, !ignoredApps.contains(front?.bundleIdentifier ?? "") else { matcher.reset(); return Unmanaged.passUnretained(event) }
        if pid != lastPID || Date().timeIntervalSince(lastTime) > 3 { matcher.reset() }
        lastPID = pid; lastTime = Date()
        let code = event.getIntegerValueField(.keyboardEventKeycode)
        guard !event.flags.contains(.maskCommand), !event.flags.contains(.maskControl), !event.flags.contains(.maskAlternate), ![51, 53, 123, 124, 125, 126, 36, 48, 117].contains(code) else { matcher.reset(); return Unmanaged.passUnretained(event) }
        var length = 0
        var chars = [UniChar](repeating: 0, count: 8)
        event.keyboardGetUnicodeString(maxStringLength: 8, actualStringLength: &length, unicodeString: &chars)
        let text = String(utf16CodeUnits: chars, count: length)
        guard let item = matcher.feed(text, snippets: store.items), item.text.utf16.count <= 2000, let keyword = item.keyword else { return Unmanaged.passUnretained(event) }
        // The final keyword character is suppressed; delete only characters already delivered.
        for _ in 0..<(keyword.count - 1) { postKey(CGKeyCode(kVK_Delete), proxy: proxy) }
        // Unicode events avoid changing the clipboard during expansion.
        var chunks: [[UniChar]] = []
        var current: [UniChar] = []
        for scalar in item.text.unicodeScalars {
            let units = Array(String(scalar).utf16)
            if current.count + units.count > 20 { chunks.append(current); current = [] }
            current.append(contentsOf: units)
        }
        if !current.isEmpty { chunks.append(current) }
        for chunk in chunks {
            let output = CGEvent(keyboardEventSource: nil, virtualKey: 0, keyDown: true)
            output?.flags = []
            output?.setIntegerValueField(.eventSourceUserData, value: generatedEventTag)
            chunk.withUnsafeBufferPointer { output?.keyboardSetUnicodeString(stringLength: chunk.count, unicodeString: $0.baseAddress) }
            output?.tapPostEvent(proxy)
            let up = CGEvent(keyboardEventSource: nil, virtualKey: 0, keyDown: false)
            up?.flags = []; up?.setIntegerValueField(.eventSourceUserData, value: generatedEventTag); up?.tapPostEvent(proxy)
        }
        return nil
    }
}
