"""Finder layout, in points; artwork is generated by make-dmg-background.swift."""
import os

format = "UDZO"
filesystem = "HFS+"
files = [defines["app"]]
symlinks = {"Applications": "/Applications"}
icon = os.path.join(defines["app"], "Contents", "Resources", "Snippet.icns")
background = defines["background"]
window_rect = ((240, 180), (680, 440))
default_view = "icon-view"
show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
include_icon_view_settings = True
include_list_view_settings = False
arrange_by = None
scroll_position = (0, 0)
icon_size = 88
text_size = 13
label_pos = "bottom"
icon_locations = {"Snippet.app": (190, 226), "Applications": (490, 226)}
